replicaCount: 3

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

migrationsEnable: true
commonEnvFrom: []


podAnnotations: { }

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: { }
  hosts: []
  #  hosts:
  #    - host: ""
  #      paths:
  #        - path: /
  #          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 1000m
    memory: 128Mi
  limits:
    memory: 256Mi

redis:
  enabled: true
  image: redis:7
  resources:
    requests:
      memory: 64Mi
      cpu: 250m
    limits:
      memory: 256Mi

celery:
  enabled: true
  redisConfigMap: true
  envFrom: []
  entrypoint: tasks.__main__.app
  beat:
    resources:
      requests:
        cpu: 1000m
        memory: 128Mi
      limits:
        memory: 256Mi
  worker:
    replicas: 1
    concurrency: 1
    resources:
      requests:
        cpu: 1000m
        memory: 128Mi
      limits:
        memory: 256Mi
