image:
  repository: "fastapi"
  pullPolicy: Never
  tag: ""

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: fastapi.localhost
      paths:
        - path: /
          pathType: Prefix
          serviceName: fastapi
          servicePortName: http
  tls: []

commonEnvFrom:
  - secretRef:
      name: database-secret
    prefix: database_

api:
  replicaCount: 1
  resources:
    requests:
      cpu: 250m

# We don't want to run migrations automatically in most cases during development
migrations:
  enabled: false
