image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""
podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

migrations:
  enabled: true
  command: ["alembic", "upgrade", "head"]
  resources: {}

api:
  enabled: true
  args: ["--port", "8000"]
  replicaCount: 3
  probePath: /health
  containerPort: 8000
  antiAffinity:
    enable: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi

  tmpfs:
    enabled: false
    sizeLimit: 1Gi

  ingress:
    enabled: true
    className: "nginx"
    annotations: {}
    host: ""
    path: /
    pathType: Prefix
    tls: []

cronjobs:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi
  tasks: []
#    task-name:
#      schedule: "* * * * *"
#      entrypoint: ["python", "-m", "package.module"]
#    task-name1:
#      schedule: "* * * * *"
#      suspended: true
#      entrypoint: ["python", "-m", "package.module"]

commonEnvFrom: []
imagePullSecrets: []
