{{- if and .Values.enabled .Values.networkPolicy.enabled  -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}

spec:
  podSelector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "common.selectorLabels" . | nindent 14 }}

  policyTypes:
    - Ingress

{{- end -}}
