{{ $fullname := include "app.fullname" . }}
{{ $labels := include "worker.labels" . }}
{{ $selectorLabels := include "worker.selectorLabels" . }}

{{ range $name, $workerDef := .Values.workers.defs }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}-{{ $name }}
  labels:
    {{- $labels | nindent 4 }}
    worker-name: "{{ $name }}"
spec:
  replicas: 1

  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- $.Values.podAnnotations | toYaml | nindent 8 }}
      labels:
        {{- $selectorLabels | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml $.Values.imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- $.Values.common.volumes | toYaml | nindent 8 }}
      containers:
        - name: worker
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command:
            {{ range $workerDef.entrypoint }}
            - {{ . | quote }}
            {{ end }}
          args:
            {{ range $workerDef.args }}
            - {{ . | quote }}
            {{ end }}
          envFrom:
            {{- $.Values.common.envFrom | toYaml | nindent 12 }}
          resources:
            {{- toYaml $.Values.workers.resources | nindent 12 }}
          volumeMounts:
            {{- $.Values.common.volumeMounts | toYaml | nindent 12 }}
---
{{- end -}}
