{{- if .Values.api.enabled  -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- .Values.podAnnotations | toYaml | nindent 8 }}
      labels:
        {{- include "api.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- .Values.imagePullSecrets | toYaml | nindent 8 }}
      securityContext:
        {{- .Values.podSecurityContext | toYaml | nindent 8 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    {{- include "api.selectorLabels" . | nindent 20 }}
              weight: 100
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- .Values.securityContext | toYaml | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- .Values.api.args | toYaml | nindent 12 }}
          envFrom:
            {{- .Values.commonEnvFrom | toYaml | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.api.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.api.probePath }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.api.probePath }}
              port: http
          resources:
            {{- .Values.api.resources | toYaml | nindent 12 }}
          {{ if .Values.api.tmpfs.enabled -}}
          volumeMounts:
            - mountPath: /tmp
              name: {{- include "api.tmpfsVolumeName" . }}
          {{- end }}
      {{ if .Values.api.tmpfs.enabled -}}
      volumes:
        - name:  {{- include "api.tmpfsVolumeName" . }}
          emptyDir:
            sizeLimit: {{ .Values.api.tmpfs.sizeLimit }}
      {{- end }}
{{- end -}}
