{{- if .Values.migrations.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.fullname" . }}-migrate
  labels:
    {{- include "migrations.labels" . | nindent 4}}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade

spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "migrations.labels" . | nindent 8}}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ .Values.migrations.command }}
          envFrom:
            {{ .Values.commonEnvFrom | toYaml | nindent 12}}
          resources:
            {{- toYaml .Values.migrations.resources | nindent 12 }}
{{- end -}}
