{{- if .Values.celery.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-celery-worker
  labels:
    {{- include "celery-worker.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.celery.worker.replicas }}
  selector:
    matchLabels:
      {{- include "celery-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "celery-worker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "app.fullname" . }}-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - celery
            - --app
            - {{ .Values.celery.entrypoint }}
            - worker
            - --concurrency
            - {{ .Values.celery.worker.concurrency | quote }}
            - -l
            - INFO
          envFrom:
            {{ .Values.commonEnvFrom | toYaml | nindent 12 }}
            {{- if .Values.celery.redisConfigMap }}
            - configMapRef:
                name: {{ include "celery.redisConfigMapName" . }}
              prefix: celery_
            {{- end }}
          resources:
            {{- toYaml .Values.celery.worker.resources | nindent 12 }}
{{- end -}}
