name: Lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.12.7
        job:
          - deptry src
          - mypy .
          - ruff format --check .
          - ruff check .

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache PIP
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .venv
          key: pip-${{ matrix.python-version }}-${{ hashFiles('pdm.lock') }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - run: uv run ${{ matrix.job }}
