name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.1-bookworm
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.9
      - name: Cache PIP
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .venv
          key: pip-${{ matrix.python-version }}-${{ hashFiles('pdm.lock') }}
      - name: Install PDM
        run: |
          pip install pdm
          pdm sync --clean

      - run: |
          pdm run coverage run
          pdm run coverage report -m
          pdm run coverage xml
        env:
          DATABASE_TEST_URL: "postgresql+asyncpg://postgres:password@localhost/postgres"
          DATABASE_NAME: " "
          DATABASE_HOST: " "
          DATABASE_USERNAME: " "
          DATABASE_PASSWORD: " "
