name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.1-bookworm
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.3
      - name: Cache PIP
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .venv
          key: pip-${{ matrix.python-version }}-${{ hashFiles('pdm.lock') }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - run: |
          uv run pytest --reuse-db -n auto --cov --cov-report=xml:coverage/coverage.xml
        env:
          DATABASE_TEST_URL: "postgresql+asyncpg://postgres:password@localhost/postgres"
          DATABASE_NAME: " "
          DATABASE_HOST: " "
          DATABASE_USERNAME: " "
          DATABASE_PASSWORD: " "
